# Generated by Django 5.2.3 on 2025-07-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Item')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Item')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='academia_virtual/', verbose_name='Imagem do Item')),
            ],
            options={
                'verbose_name': 'Item de Academia',
                'verbose_name_plural': 'Itens de Academia',
                'ordering': ['nome'],
            },
        ),
    ]
