# Generated by Django 5.2.3 on 2025-07-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_virtual', '0005_exercicio_treino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='exercicios',
        ),
        migrations.DeleteModel(
            name='Exercicio',
        ),
        migrations.DeleteModel(
            name='Treino',
        ),
    ]
