# Generated by Django 5.2.3 on 2025-07-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viagem_mot',
            old_name='Mês',
            new_name='mês',
        ),
        migrations.RemoveField(
            model_name='viagem_cam',
            name='marca',
        ),
    ]
