# Generated by Django 5.2.3 on 2025-07-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0002_rename_mês_viagem_mot_mês_remove_viagem_cam_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caminhao',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca do Caminhão'),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
