# Generated by Django 5.2.3 on 2025-07-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0004_alter_caminhao_options_alter_motorista_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave de Configuração')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(default='geral', max_length=50, verbose_name='Categoria')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'ordering': ['categoria', 'chave'],
            },
        ),
    ]
