# Generated by Django 5.2.3 on 2025-07-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0006_empresa_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca da Unidade'),
        ),
    ]
