# Generated by Django 5.2.3 on 2025-07-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0007_unidade_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa da Unidade'),
        ),
    ]
