# Generated by Django 5.2.3 on 2025-07-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0008_unidade_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quilometragem', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Quilometragem Atual (km)')),
                ('Consumido', models.PositiveIntegerField(blank=True, default=0.0, null=True, verbose_name='Combustível Total (litros)')),
                ('Quilometragem_média', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Média de Consumo (km/l)')),
                ('Horas_de_motor', models.CharField(blank=True, default=0.0, max_length=100, null=True, verbose_name='Horas de Motor')),
                ('Velocidade_média', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Velocidade Média (km/h)')),
                ('RPM_médio', models.FloatField(blank=True, default=0.0, null=True, verbose_name='RPM Médio do Motor')),
                ('Temperatura_média', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Temperatura Média (°C)')),
                ('Emissões_CO2', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Emissões de CO2 (g/km)')),
                ('período', models.CharField(blank=True, default='Maio', max_length=20, null=True, verbose_name='Período de Referência')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='umbrella360.unidade')),
            ],
        ),
    ]
