# Generated by Django 5.2.3 on 2025-08-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0009_viagem_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='senha',
            field=models.CharField(blank=True, default='senha', max_length=100, null=True, verbose_name='Senha de Acesso'),
        ),
    ]
