# Generated by Django 5.2.3 on 2025-08-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0010_empresa_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Token de Acesso Wialon'),
        ),
    ]
