# Generated by Django 5.2.3 on 2025-08-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0011_empresa_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='nm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Unidade'),
        ),
    ]
