# Generated by Django 5.2.3 on 2025-08-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0012_alter_unidade_nm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cerca Eletrônica')),
                ('data_entrada', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('duracao', models.DurationField(blank=True, null=True, verbose_name='Duração')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='umbrella360.unidade')),
            ],
        ),
    ]
