# Generated by Django 5.2.3 on 2025-08-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0013_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='período',
            field=models.CharField(blank=True, default='Maio', max_length=20, null=True, verbose_name='Período de Referência'),
        ),
    ]
