# Generated by Django 5.2.3 on 2025-08-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0014_checkpoint_período'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'ordering': ['-data_entrada'], 'verbose_name': 'CheckPoint', 'verbose_name_plural': 'CheckPoints'},
        ),
    ]
