# Generated by Django 5.2.3 on 2025-08-08 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0015_alter_checkpoint_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrações',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data da Infração')),
                ('limite', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Limite de Velocidade (km/h)')),
                ('velocidade', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Velocidade (km/h)')),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infracoes', to='umbrella360.unidade')),
            ],
            options={
                'verbose_name': 'Infração',
                'verbose_name_plural': 'Infrações',
                'ordering': ['-data'],
            },
        ),
    ]
