# Generated by Django 5.2.3 on 2025-08-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0016_infrações'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrações',
            name='localizacao',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Localização'),
        ),
    ]
