# Generated by Django 5.2.3 on 2025-08-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0017_alter_infrações_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='id_recurso',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID do Recurso Wialon'),
        ),
    ]
