# Generated by Django 5.2.3 on 2025-08-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0018_empresa_id_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='odometro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Odômetro (km)'),
        ),
    ]
