# Generated by Django 5.2.3 on 2025-08-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0019_unidade_odometro'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_base',
            name='motor_ocioso',
            field=models.DurationField(blank=True, null=True, verbose_name='Horas de Motor Ocioso'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='período',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Referência'),
        ),
        migrations.AlterField(
            model_name='viagem_base',
            name='período',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Referência'),
        ),
    ]
