# Generated by Django 5.2.3 on 2025-09-01 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0020_viagem_base_motor_ocioso_alter_checkpoint_período_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('unidade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='umbrella360.unidade')),
                ('ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano do Veículo')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do Veículo')),
                ('cor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor do Veículo')),
                ('tipo_combustivel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Combustível')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['modelo'],
            },
            bases=('umbrella360.unidade',),
        ),
    ]
