# Generated by Django 5.2.3 on 2025-09-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0021_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista_Unidade',
            fields=[
                ('unidade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='umbrella360.unidade')),
                ('pontuacao', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Pontuação do Motorista')),
            ],
            bases=('umbrella360.unidade',),
        ),
    ]
