# Generated by Django 5.2.3 on 2025-09-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0022_motorista_unidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Motorista_Unidade',
        ),
    ]
