# Generated by Django 5.2.3 on 2025-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0023_delete_motorista_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='frota',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID da Frota Wialon'),
        ),
    ]
