# Generated by Django 5.2.3 on 2025-09-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0024_empresa_frota'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='id_wialon',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Wialon'),
        ),
    ]
