# Generated by Django 5.2.3 on 2025-09-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0025_unidade_id_wialon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagem_base',
            options={'ordering': ['-período'], 'verbose_name': 'Viagem Base', 'verbose_name_plural': 'Viagens'},
        ),
        migrations.AlterField(
            model_name='viagem_base',
            name='quilometragem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Quilometragem'),
        ),
    ]
