# Generated by Django 5.2.3 on 2025-09-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0026_alter_viagem_base_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='id_criador',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Criador no Wialon'),
        ),
    ]
