# Generated by Django 5.2.3 on 2025-09-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0027_empresa_id_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='id_criador',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Criador no Wialon'),
        ),
    ]
