# Generated by Django 5.2.3 on 2025-10-04 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0028_unidade_id_criador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem_eco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('rpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='RPM do Motor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_eco', to='umbrella360.unidade')),
            ],
            options={
                'verbose_name': 'Viagem Ecológica',
                'verbose_name_plural': 'Viagens Ecológicas',
            },
        ),
    ]
