# Generated by Django 5.2.3 on 2025-10-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0029_viagem_eco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem_eco',
            name='timestamp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Timestamp'),
        ),
    ]
