# Generated by Django 5.2.3 on 2025-10-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0030_alter_viagem_eco_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_eco',
            name='altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Altitude (m)'),
        ),
        migrations.AddField(
            model_name='viagem_eco',
            name='velocidade',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidade (km/h)'),
        ),
    ]
