# Generated by Django 5.2.3 on 2025-10-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0031_viagem_eco_altitude_viagem_eco_velocidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem_Detalhada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_inicial', models.PositiveIntegerField(blank=True, null=True, verbose_name='Timestamp Inicial')),
                ('timestamp_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='Timestamp Final')),
            ],
        ),
    ]
