# Generated by Django 5.2.3 on 2025-10-13 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0032_viagem_detalhada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem_detalhada',
            name='id',
        ),
        migrations.AddField(
            model_name='viagem_detalhada',
            name='viagem_base_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='umbrella360.viagem_base'),
            preserve_default=False,
        ),
    ]
