# Generated by Django 5.2.3 on 2025-10-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0033_remove_viagem_detalhada_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagem_detalhada',
            options={'ordering': ['-período'], 'verbose_name': 'Viagem Detalhada', 'verbose_name_plural': 'Viagens Detalhadas'},
        ),
    ]
