# Generated by Django 5.2.3 on 2025-10-15 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0034_alter_viagem_detalhada_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_detalhada',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veículo', to='umbrella360.veiculo'),
        ),
    ]
