# Generated by Django 5.2.3 on 2025-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0035_viagem_detalhada_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem_detalhada',
            name='veiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
