# Generated by Django 5.2.3 on 2025-10-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0036_alter_viagem_detalhada_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_eco',
            name='energia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Energia (V)'),
        ),
    ]
