# Generated by Django 5.2.3 on 2025-10-23 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0037_viagem_eco_energia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('unidade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='umbrella360.unidade')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Código')),
                ('avl_driver', models.PositiveIntegerField(blank=True, null=True, verbose_name='avl_driver')),
            ],
            bases=('umbrella360.unidade',),
        ),
    ]
