# Generated by Django 5.2.3 on 2025-10-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0038_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código'),
        ),
    ]
