# Generated by Django 5.2.3 on 2025-10-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0039_alter_driver_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_eco',
            name='avl_driver',
            field=models.IntegerField(blank=True, null=True, verbose_name='Motorista'),
        ),
    ]
