# Generated by Django 5.2.3 on 2025-10-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0040_viagem_eco_avl_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_eco',
            name='driver_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Motorista'),
        ),
    ]
