# Generated by Django 5.2.3 on 2025-10-23 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0041_viagem_eco_driver_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_eco',
            name='nome_motorista',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viagens_motorista', to='umbrella360.driver'),
        ),
        migrations.AlterField(
            model_name='viagem_eco',
            name='avl_driver',
            field=models.IntegerField(blank=True, null=True, verbose_name='Avl_Driver'),
        ),
    ]
