# Generated by Django 5.2.3 on 2025-10-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0042_viagem_eco_nome_motorista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_eco',
            name='faixa_amarela',
            field=models.BooleanField(blank=True, null=True, verbose_name='Faixa Amarela'),
        ),
        migrations.AddField(
            model_name='viagem_eco',
            name='faixa_azul',
            field=models.BooleanField(blank=True, null=True, verbose_name='Faixa Azul'),
        ),
        migrations.AddField(
            model_name='viagem_eco',
            name='faixa_verde',
            field=models.BooleanField(blank=True, null=True, verbose_name='Faixa Verde'),
        ),
        migrations.AddField(
            model_name='viagem_eco',
            name='faixa_vermelha',
            field=models.BooleanField(blank=True, null=True, verbose_name='Faixa Vermelha'),
        ),
    ]
