# Generated by Django 5.2.3 on 2025-10-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0043_viagem_eco_faixa_amarela_viagem_eco_faixa_azul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_eco',
            name='ocioso',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ocioso'),
        ),
    ]
