# Generated by Django 5.2.3 on 2025-10-30 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0044_viagem_eco_ocioso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatistica_Diaria_Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('total_pontos', models.IntegerField(default=0, verbose_name='Total de Pontos')),
                ('pontos_ocioso', models.IntegerField(default=0, verbose_name='Pontos em Ocioso')),
                ('pontos_faixa_azul', models.IntegerField(default=0, verbose_name='Pontos Faixa Azul')),
                ('pontos_faixa_verde', models.IntegerField(default=0, verbose_name='Pontos Faixa Verde')),
                ('pontos_faixa_amarela', models.IntegerField(default=0, verbose_name='Pontos Faixa Amarela')),
                ('pontos_faixa_vermelha', models.IntegerField(default=0, verbose_name='Pontos Faixa Vermelha')),
                ('perc_ocioso', models.FloatField(default=0.0, verbose_name='% Ocioso')),
                ('perc_faixa_azul', models.FloatField(default=0.0, verbose_name='% Faixa Azul')),
                ('perc_faixa_verde', models.FloatField(default=0.0, verbose_name='% Faixa Verde')),
                ('perc_faixa_amarela', models.FloatField(default=0.0, verbose_name='% Faixa Amarela')),
                ('perc_faixa_vermelha', models.FloatField(default=0.0, verbose_name='% Faixa Vermelha')),
                ('score_performance', models.FloatField(default=0.0, verbose_name='Score de Performance')),
                ('rpm_medio', models.FloatField(default=0.0, verbose_name='RPM Médio')),
                ('velocidade_media', models.FloatField(default=0.0, verbose_name='Velocidade Média')),
                ('timestamp_inicio', models.IntegerField(blank=True, null=True, verbose_name='Timestamp Início do Dia')),
                ('timestamp_fim', models.IntegerField(blank=True, null=True, verbose_name='Timestamp Fim do Dia')),
                ('horas_trabalhadas', models.FloatField(default=0.0, verbose_name='Horas Trabalhadas')),
                ('total_veiculos', models.IntegerField(default=0, verbose_name='Total de Veículos Diferentes')),
                ('veiculos_ids', models.TextField(blank=True, null=True, verbose_name='IDs dos Veículos (JSON)')),
                ('data_processamento', models.DateTimeField(auto_now=True, verbose_name='Data de Processamento')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas_diarias', to='umbrella360.driver')),
            ],
            options={
                'verbose_name': 'Estatística Diária do Motorista',
                'verbose_name_plural': 'Estatísticas Diárias dos Motoristas',
                'ordering': ['-data', 'motorista'],
                'indexes': [models.Index(fields=['motorista', 'data'], name='umbrella360_motoris_f9c09a_idx'), models.Index(fields=['data'], name='umbrella360_data_3fa77f_idx'), models.Index(fields=['score_performance'], name='umbrella360_score_p_e93bb3_idx')],
                'unique_together': {('motorista', 'data')},
            },
        ),
    ]
