# Generated by Django 5.2.3 on 2025-10-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0045_estatistica_diaria_motorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatistica_diaria_motorista',
            name='Quilometragem_média',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Média de Consumo (km/l)'),
        ),
    ]
