# Generated by Django 5.2.3 on 2025-10-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0046_estatistica_diaria_motorista_quilometragem_média'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatistica_diaria_motorista',
            name='consumo_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Consumo Total (litros)'),
        ),
        migrations.AddField(
            model_name='estatistica_diaria_motorista',
            name='quilometragem_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Quilometragem Total (km)'),
        ),
        migrations.AddField(
            model_name='estatistica_diaria_motorista',
            name='total_viagens_detalhadas',
            field=models.IntegerField(default=0, verbose_name='Total de Viagens Detalhadas'),
        ),
    ]
