# Generated by Django 5.2.3 on 2025-10-22 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=2, null=True)),
                ('populacao', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleTrendsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=200)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('interesse', models.IntegerField(blank=True, null=True)),
                ('termos_comparados', models.TextField(blank=True, null=True)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_trends_data', to='lab_01.regiao')),
            ],
        ),
    ]
