# Generated by Django 5.2.3 on 2025-10-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_01', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='pesquisa', max_length=128),
        ),
    ]
