# Generated by Django 5.2.3 on 2025-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_01', '0003_remove_usuario_data_criacao_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
