# Generated by Django 5.2.3 on 2025-10-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_01', '0004_alter_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=200)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('total_videos', models.IntegerField(default=0)),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('termo', 'data_inicial', 'data_final')},
            },
        ),
    ]
