# Generated by Django 5.2.3 on 2025-07-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0003_alter_caminhao_marca_delete_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caminhao',
            options={'ordering': ['agrupamento'], 'verbose_name': 'Caminhão', 'verbose_name_plural': 'Caminhões'},
        ),
        migrations.AlterModelOptions(
            name='motorista',
            options={'ordering': ['agrupamento'], 'verbose_name': 'Motorista', 'verbose_name_plural': 'Motoristas'},
        ),
        migrations.AlterModelOptions(
            name='viagem_cam',
            options={'verbose_name': 'Viagem Caminhões', 'verbose_name_plural': 'Viagens Caminhões'},
        ),
        migrations.AlterModelOptions(
            name='viagem_mot',
            options={'verbose_name': 'Viagem Motorista', 'verbose_name_plural': 'Viagens Motoristas'},
        ),
    ]
