# Generated by Django 5.2.3 on 2025-07-24 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0005_configuracaosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('nm', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nome da Unidade')),
                ('cls', models.CharField(blank=True, max_length=50, null=True, verbose_name='Classe da Unidade')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID da Unidade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Unidade')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umbrella360.empresa', verbose_name='Empresa Associada')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['id'],
            },
        ),
    ]
