# Generated by Django 5.2.3 on 2025-07-29 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_virtual', '0002_equipamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Área')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Área')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='academia_virtual/', verbose_name='Imagem da Área')),
            ],
            options={
                'verbose_name': 'Área de Academia',
                'verbose_name_plural': 'Áreas de Academia',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia_virtual.area', verbose_name='Área Associada'),
        ),
    ]
