# Generated by Django 5.2.3 on 2025-07-29 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_virtual', '0003_area_equipamento_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('itemacademia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academia_virtual.itemacademia')),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidade do Professor')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
            bases=('academia_virtual.itemacademia',),
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nome'], 'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='equipamento',
            options={'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='itemacademia',
            options={'ordering': ['nome'], 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
    ]
